### ISSUE TITLE
free() calls missing in ariettag25/pwm_dev/src/PWM_lib.c

### ISSUE THREAD

**Issue by amontefusco** [cledic/ariettag25#1]
Looking at your PWM library

 ariettag25/pwm_dev/src/PWM_lib.c

it seems that free() functions are missing in your code.
As is, the library functions are producing memory leakage: you should add the free() calls in order to deallocate buffers, or, even better, don't use dynamic allocation at all, and declare the buffers as automatic variables.
Moreover, it would preferable to use snprintf insteaf of sprintf in order to do a bit of sanity check.

For example:

int PWMChannel_SetPeriod( char\* chnl, char\* period)
{
int fchnl;
char buff [256];  // automatic variable

snprintf( buff, sizeof(buff), "/sys/class/pwm/pwmchip0/pwm%s/enable", chnl); // 
....
....

and so on for the other functions.

**Comment by cledic** [comment]
Hello Andrea,
thanks a lot for the correction. I will add the free() statement. And I
will double check the other sources. :-)

> even better, don't use dynamic allocation at all...
> what is wrong about dynamic allocation? :-)

Regards
Clemente

**Comment by amontefusco** [comment]
> > what is wrong about dynamic allocation? :-) 

In general, nothing.
In your case, though, you are using that buffers just locally, so an automatic local variable it is better, especially into the more frequently called functions, in order to avoid the burden of call the dynamic allocator twice for each main function call.
An automatic variable consumes only a pointer move into the stack frame (assuming one has enough space in the stack).

Ciao

  _am_
